apiVersion: v1
kind: ReplicationController
metadata:
  name: blue
  label:
    app:blue
spec:
  replicas: 1
  selector:
    app: blue
  template:
    metadata:
      name: blue
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: emrepacaci/cloudcapstonev1
        ports:
	- name: http-server
        - containerPort: 80
