apiVersion: v1
kind: Service
metadata:
  name: bluegreenlb
  labels:
    app: bluegreenlb

spec:
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer       

