apiVersion: v1
kind: ReplicationController
metadata:
  name: green
  label:
    app:green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      name: green
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: emrepacaci/cloudcapstonev1
        ports:
	- name: http-server
        - containerPort: 80
